<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '253c157292f75eb38082b5acb06f3f01' => $vendorDir . '/nikic/fast-route/src/functions.php',
    'a80a00e91dfb988b39fee09aeaac3a1e' => $vendorDir . '/simple-swoole/simps/src/functions.php',
    'bc5329889c908156074ca6ae6039fc38' => $baseDir . '/utils/clover/nano/functions.php',
);
