<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit114dcccc0c3f36c19949911df4d78361
{
    public static $files = array (
        '253c157292f75eb38082b5acb06f3f01' => __DIR__ . '/..' . '/nikic/fast-route/src/functions.php',
        'a80a00e91dfb988b39fee09aeaac3a1e' => __DIR__ . '/..' . '/simple-swoole/simps/src/functions.php',
        'bc5329889c908156074ca6ae6039fc38' => __DIR__ . '/../..' . '/utils/clover/nano/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Simps\\DB\\' => 9,
            'Simps\\' => 6,
        ),
        'M' => 
        array (
            'Module\\' => 7,
            'Model\\' => 6,
        ),
        'F' => 
        array (
            'FastRoute\\' => 10,
        ),
        'E' => 
        array (
            'Exception\\' => 10,
        ),
        'C' => 
        array (
            'Clover\\Nano\\' => 12,
        ),
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Simps\\DB\\' => 
        array (
            0 => __DIR__ . '/..' . '/simple-swoole/db/src',
        ),
        'Simps\\' => 
        array (
            0 => __DIR__ . '/..' . '/simple-swoole/simps/src',
        ),
        'Module\\' => 
        array (
            0 => __DIR__ . '/../..' . '/modules',
        ),
        'Model\\' => 
        array (
            0 => __DIR__ . '/../..' . '/models',
        ),
        'FastRoute\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/fast-route/src',
        ),
        'Exception\\' => 
        array (
            0 => __DIR__ . '/../..' . '/exceptions',
        ),
        'Clover\\Nano\\' => 
        array (
            0 => __DIR__ . '/../..' . '/utils/clover/nano',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/apps',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit114dcccc0c3f36c19949911df4d78361::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit114dcccc0c3f36c19949911df4d78361::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
